import { motion } from "motion/react";

const sections = [
  {
    title: "Your Privacy",
    body: `Your privacy is important to us. To better protect your privacy we provide this notice explaining our online information practices and the choices you can make about the way your information is collected and used. You agree to these policies by virtue of using our website in a way that leads to you providing us with personal information.`,
  },
  {
    title: "State Law & Accompanying Rights",
    body: `Please understand that you may have additional rights originating from State laws based on where you live. These State-based rights may augment, strengthen, or otherwise complement any privacy rights you have inherently or under Federal law. Our policy is to comply fully with the privacy policies of every jurisdiction in which we operate. Accordingly, you are free to use our contact information to reach us at any time to assert any State rights.`,
  },
  {
    title: "Our Commitment To Children's Privacy",
    body: `Protecting the privacy of the very young is especially important. For that reason, our website will never collect or maintain information from those we actually know are under 18, and no part of our website is structured to attract anyone under 18.\n\nUnder our Terms of Service and Conditions of Use, children under 18 are not allowed to use our website and access our services. It is not our intention to offer products or services to minors.`,
  },
  {
    title: "Google Analytics",
    body: `Gadgetlesstech uses Google Analytics to help analyse how users use the site. The tool uses "cookies," which are text files placed on your computer, to collect standard Internet log information and visitor behaviour information in an anonymous form. The information generated by the cookie about your use of the website (including your IP address) is transmitted to Google. This information is then used to evaluate visitors' use of this website and to compile statistical reports on website activity.\n\nWe will never (and will not allow any third party to) use the statistical analytics tool to track or to collect any Personally Identifiable Information of visitors to our site. Google will not associate your IP address with any other data held by Google. Neither we nor Google will link, or seek to link, an IP address with the identity of a computer user.\n\nYou may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.`,
  },
  {
    title: "Other Collection of Personal Information",
    body: `When visiting our website, the IP address used to access our website may be logged along with the dates and times of access. This information is purely used to analyze trends, administer our website, track users movement, and gather broad demographic information for internal use such as statistical assessments and website improvement. Most importantly, any recorded IP addresses are not linked to personally identifiable information.\n\nOther information may be collected as well, which is rather typical of most websites. For instance, the source that referred you to our website is generally known. Likewise, your duration on our website, and your destination when you leave our website can also be tracked. Other common data collected includes the type of operating system and web browser you are using.\n\nCookies are a key means of improving user experience by allowing us to customize your use of our website. Simple information is transferred to your computer to allow the content and experience to reflect your actions and preferences. You are free to make adjustments in your web browser to disable cookies or receive notification of them. Please understand that refusing cookies may cripple some website features.\n\nAt times, you will be fully aware of information received, as you are the direct source providing it — such as commenting on a blog post, providing an email address, completing a survey, or making a purchase. Refusing to provide some of this information may result in us being unable to provide the products or services you've requested.`,
  },
  {
    title: "Handling of Personal Information",
    body: `Any personal information you provide to others apart from us or our vendors is wholly optional. Our primary intention for collecting personal and private information from you is simply to conduct our business. We see no reason to share your personal information with outside parties unless you have authorized us to do so.\n\nThere are instances where your information is stored with third-party service providers, such as email service providers. However, you are never required to deal with any such third party directly, they are limited in how they use your information, and they cannot sell or transfer it to others.\n\nAggregate, non-individual information about our website visitors as a whole may be shared with third parties for various purposes at our sole discretion.\n\nThere may be times when we are legally compelled to share your information — for instance, in cases of illegal activity, serious allegations, suspected copyright infringement, or other intellectual property violations. We reserve the right to share your information in those circumstances or when required by law.`,
  },
  {
    title: "Google Adsense and the DoubleClick DART Cookie",
    body: `Google, as a third-party advertisement vendor, may use cookies to serve ads on this website. The use of DART cookies by Google enables them to serve adverts to visitors based on their visits to this website and other websites on the internet. To opt out of the DART cookies you may visit the Google ad and content network privacy policy at http://www.google.com/privacy_ads.html.\n\nOther third-party ad servers or ad networks may also use cookies to track user activity on this website to measure advertisement effectiveness. Our website has no access or control over these cookies. You can opt out of some of these cookies at http://www.networkadvertising.org/managing/opt_out.asp.`,
  },
  {
    title: "Links to Third Party Websites",
    body: `We have included links on this website for your use and reference. We are not responsible for the privacy policies on these websites. You should be aware that the privacy policies of these websites may differ from our own.`,
  },
  {
    title: "Comments Policy",
    body: `By posting on our blog, you agree to the following:\n\nYou may comment without registering. You may post anonymously, though we don't recommend it. You may post follow-up questions — we prefer public comments over private emails so answers benefit everyone. You may disagree with us, provided you do so respectfully.\n\nGadgetlesstech reserves the right to delete comments that are, in our sole opinion: (a) snarky; (b) off-topic; (c) libelous, defamatory, abusive, harassing, threatening, profane, pornographic, offensive, false, or misleading; or (d) spam.\n\nYou retain ownership of your comments. By commenting, you grant Gadgetlesstech a worldwide, irrevocable, non-exclusive, royalty-free license to store, use, transmit, display, publish, reproduce, and distribute your comments in any format.`,
  },
  {
    title: "Change Notice",
    body: `As with any of our administrative and legal notice pages, the contents of this page can and will change over time. These changes are carried out by Gadgetlesstech in order to protect you and our website. If this page is important to you, you should check back frequently as no other notice of changed content will be provided.`,
  },
  {
    title: "Copyright Warning",
    body: `The legal notices and administrative pages on this website, including this one, have been diligently drafted by an attorney. We have paid to license the use of these legal notices for your protection and ours. This material may not be used in any way for any reason and unauthorized use is policed via Copyscape to detect violators.`,
  },
  {
    title: "Questions / Comments / Concerns",
    body: `If you have any questions about the contents of this page, or simply wish to reach us for any other reason, you may do so by emailing: support@gadgetlesstech.com`,
  },
];

export default function PrivacyPolicy() {
  return (
    <div className="pt-32 pb-32 bg-black min-h-screen relative overflow-hidden">
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-cyan-500/5 rounded-full blur-[120px] pointer-events-none" />

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-16">
          <span className="text-cyan-400 font-black uppercase tracking-[0.3em] text-[12px] mb-6 block flex items-center">
            <div className="w-12 h-px bg-cyan-400/30 mr-4" />
            Legal
          </span>
          <h1 className="font-display text-5xl md:text-7xl font-black tracking-tighter text-white mb-6 uppercase italic leading-[0.9]">
            Privacy <span className="text-cyan-400">Policy</span>
          </h1>
          <p className="text-gray-500 text-sm font-medium">
            Gadgetlesstech &mdash; Last updated 2026
          </p>
        </motion.div>

        <div className="space-y-12">
          {sections.map((section, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.05 * i }}
              className="border-t border-white/5 pt-10"
            >
              <h2 className="font-display font-black text-white uppercase tracking-tighter text-xl italic mb-4">
                {section.title}
              </h2>
              <div className="space-y-4">
                {section.body.split("\n\n").map((para, j) => (
                  <p key={j} className="text-gray-400 text-sm font-medium leading-relaxed">
                    {para}
                  </p>
                ))}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}
